package org.kie.kogito.codegen.tests;
unit BusinessRuleUnit;
import org.kie.kogito.codegen.data.Person;

rule isAdult
    when
        $person : /persons
    then
        System.out.println("Person " + $person.getName() + " is adult");
		$person.setAdult(true);
end


rule hasString
    when
        $string : /strings
    then
        System.out.println("Found String " + $string);
        System.out.println("also there is a global " + myGlobal);

end


