package com.sample;

import org.jbpm.bpmn2.objects.Address;
import org.jbpm.bpmn2.objects.Person;

global java.util.List listPerson;
global java.util.List listAddress;

rule PersonRule ruleflow-group "person-rules"
  when
    $p : Person()
  then
    System.out.println("Found person " + $p.getName());
    listPerson.add($p.getName());
end


rule AddressRule ruleflow-group "address-rules"
  when
    $a : Address()
  then
    System.out.println("Found address " + $a.getStreet());
    listAddress.add($a.getStreet());
end