package com.sample;

import org.kie.api.runtime.process.WorkflowProcessInstance
import org.kie.kogito.internal.process.runtime.KogitoProcessRuntime
import org.kie.kogito.internal.process.runtime.KogitoProcessInstance
import org.kie.kogito.internal.process.runtime.KogitoProcessInstance
import org.jbpm.process.instance.InternalProcessRuntime


global java.util.List list;

rule MyRule
  ruleflow-group "myRules"
  when
    processInstance : WorkflowProcessInstance()
    eval( processInstance.getVariable("x") == "SomeString")
  then
    processInstance = (WorkflowProcessInstance)InternalProcessRuntime.asKogitoProcessRuntime( kcontext.getKieRuntime() ).getProcessInstance(((KogitoProcessInstance)processInstance).getStringId());
    processInstance.setVariable("x", "AnotherString");
    list.add("Executed");
end