package defaultPackge;

import org.kie.api.runtime.process.WorkflowProcessInstance;
import org.jbpm.bpmn2.objects.Person;

rule NoPersonRule ruleflow-group "ErrorBoundaryRuleFlow"
no-loop
    when
        WorkflowProcessInstance()
        Person(name == null)
    then
        throw new NullPointerException("no person");
end

rule InvalidPersonRule ruleflow-group "ErrorBoundaryRuleFlow"
no-loop
    when
        WorkflowProcessInstance()
        Person(name == "unsupported")
    then
        throw new UnsupportedOperationException("invalid person");
end
