package org.kie.kogito.codegen.unit;
unit StockUnit;

import org.kie.kogito.codegen.data.StockTick
import org.kie.kogito.codegen.data.ValueDrop

rule CreateValueDrops when
    $s1: /stockTicks
    $s2: /stockTicks[ company == $s1.company, value < $s1.value, this after[1, 100] $s1 ] over window:length( 2 )
then
    valueDrops.add( new ValueDrop($s1.getCompany(), $s1.getValue(), $s2.getValue()) );
end

query highestValueDrop(String $company)
     $s: /valueDrops[ company == $company ]
     not /valueDrops[ company == $company, dropAmount > $s.dropAmount ]
end
