package org.kie.kogito.event;

import java.io.IOException;
import java.util.function.Function;

import io.cloudevents.CloudEvent;
import io.cloudevents.CloudEventData;

/**
 * This interface is one of the extension point for users to incorporate more event formats.
 * It is responsible for converting Cloud events generated by Kogito into the format expected by the external service.
 * Default implementation uses Jackson.
 * 
 * @param <R> The expected output type that will be consumed by the external service
 */
public interface CloudEventMarshaller<R> {
    /**
     * Convert cloud event into the type expected by the external service
     * 
     * @param event Cloud event to be converted
     * @return object to be sent to the external service
     * @throws IOException if there is a conversion problem. This method must NOT report event formatting issues through a runtime exception, it must use IOException. This way the caller
     *         can differentiate between unexpected issues and event formatting ones.
     */
    R marshall(CloudEvent event) throws IOException;

    /**
     * Convert Kogito business object into a CloudEventData for marshaling
     * 
     * @param <T> the Kogito business object type
     * @return A CloudEventData that will be marshaled.
     */
    <T> Function<T, CloudEventData> cloudEventDataFactory();
}
